name: ci-build

on:
  workflow_dispatch:
  push:
    branches: [ main, 'releases/**', error_test_branch ]
    paths:
    - '**'
  pull_request:
    branches: [ main, 'releases/**', error_test_branch ]
    paths:
    - '**'

defaults:
  run:
    working-directory: ./

jobs:
  ci-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    # Setup for .NET backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # SDK Version to use; x will use the latest version of the 8.0.x channel
    
    - name: Restore dependencies
      run: dotnet restore Full-Stack-Project.sln
    
    - name: Build
      run: dotnet build Full-Stack-Project.sln --no-restore --configuration Debug
        
    
    
      # Setup Node.js for Angular frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.1' 

    - name: Install Angular dependencies
      run: npm install
      working-directory: ./client 

    - name: Build Angular application
      run: npm build
      working-directory: ./client 

    - name: Run Angular tests
      run: npm test
      working-directory: ./client 
